plugins: [jekyll-paginate, jekyll-analytics]

exclude:
  - 'vendor'
  - 'dist.sh'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '.git'

markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tomoko
baseurl:          ''

author:
  name:           'Tomasz Krug'

paginate:         5

collections:
  tutorial:
    output: true
  docs:
    output: true

# Variables
version: 1.0.0

defaults:
  - scope:
      path: ""
      type: tutorial
    values:
      layout: tutorial
  - scope:
      path: ""
      type: docs
    values:
      layout: docs

# Analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-104345126-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
