plugins: [jekyll-paginate, jekyll-sitemap]

exclude:
  - 'vendor'
  - 'dist.sh'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '.git'

markdown:         kramdown
highlighter:      rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tomoko
url:              'https://tomoko.qubite.io'
baseurl:          ''

author:
  name:           'Tomasz Krug'

paginate:         5

collections:
  tutorial:
    output: true
  docs:
    output: true

# Variables
version: 1.0.0

defaults:
  - scope:
      path: ""
      type: tutorial
    values:
      layout: tutorial
  - scope:
      path: ""
      type: docs
    values:
      layout: docs
